### ISSUE TITLE
Feature request: filters for callback handling

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [vitaliy-ukiru/telebot-filter#5]
## The problem I'm trying to solve:
implement multiselect in as an inline keyboard where you can check and uncheck some options

## Solution that I've found out so far:
It seems that I have to generate the menu every time in order to change button text. At the same time I have to attach.

I think that I might have missed something in the telebot docs.

Nevertheless, some minimalistic example:
```golang
// this state should be stored in a db ofc
var checkboxes = map[string]bool{}

func getCheckmark(selected bool) string {
	if selected {
		return "✅ "
	}
	return ""
}

func getMultiselectKeyboard(options map[string]bool) *tele.ReplyMarkup {
	selector := &tele.ReplyMarkup{}
	btnCheckbox1 := selector.Data(getCheckmark(options["checkbox_1"])+"checkbox 1", "checkbox_1")
	btnCheckbox2 := selector.Data(getCheckmark(options["checkbox_2"])+"checkbox 2", "checkbox_2")
	selector.Inline(selector.Row(btnCheckbox1, btnCheckbox2))
	return selector
}

dp.Dispatch(
	m.New(
		fsmopt.On("/multiselect"),
		fsmopt.OnStates(fsm.AnyState),
		fsmopt.Do(func(c tele.Context, state fsm.Context) error {
			return c.Send("please select options", getMultiselectKeyboard(checkboxes))
		}),
	),
)

dp.Dispatch(
	m.New(
		fsmopt.On(tele.OnCallback),
		fsmopt.OnStates(fsm.AnyState),
		fsmopt.Filter(func(c tele.Context) bool {
			re := regexp.MustCompile(`^\f(checkbox_\d+)`)
			return re.MatchString(c.Callback().Data)
		}),
		fsmopt.Do(func(c tele.Context, state fsm.Context) error {
			re := regexp.MustCompile(`^\f(checkbox_\d+)`)
			uniqId := re.FindStringSubmatch(c.Callback().Data)
			if len(uniqId) >= 1 {
				checkboxes[uniqId[1]] = !checkboxes[uniqId[1]]
			}
			return c.Edit("please select options", getMultiselectKeyboard(checkboxes))
		}),
	),
)
```

## Propositions for the telebot-filters:

As you can see there's some custom filter used for filtering callbacks. And I would love to have some semantic sugar like pythonists have in aiogram:
```python
@router.callback_query(F.data.startswith('checkbox_'))
```
which could be transtlated in telebot-filters to something like this:
```
fsmopt.OnCallback(callback.Regexp("^checkbox_\d+$"))
```

But as far as I get it telebot-filters provide such methods only for messages and it would be nice to cover callbacks as well.

PS: It should be considered that telebot adds "\f" for inline keyboard callback unique identifiers:
https://github.com/go-telebot/telebot/blob/v3.3.6/callback.go#L87-L90

**Comment by vitaliy-ukiru** [comment]
Hi. I think you should use other way to generate callback.
In inline buttons you can provide callback unique and payload. Also it available with reply markup helpers [see](https://github.com/go-telebot/telebot/blob/a8acf843014bee762a8426a67d3b61ea4830200a/markup.go#L165).
I suggest you create button with this way:
```go
selector.Data("text1", "checkbox", "1")
selector.Data("text2", "checkbox", "2")
```

Then you can use endpoint like `"\fcheckbox"` without additional filters.
And in handler get payload:
```go
c.Data() // as strings
c.Args() // as slice of strings
c.Callback().Data // also as one string
```
The 'unique' part will be separated from the payload in either option

If you have some parts of data in `selector.Data`. It also separated by `c.Args()`

#### Refactored example
```go


const checkboxUnique = "checkbox"


func getMultiselectKeyboard(options map[string]bool) *tele.ReplyMarkup {
	selector := &tele.ReplyMarkup{}
	btnCheckbox1 := selector.Data(getCheckmark(options["1"])+"checkbox 1", checkboxUnique, "1")
	btnCheckbox2 := selector.Data(getCheckmark(options["2"])+"checkbox 2", checkboxUnique , "2")
	selector.Inline(selector.Row(btnCheckbox1, btnCheckbox2))
	return selector
}



dp.Dispatch(
	m.New(
		fsmopt.On("\f" + checkboxUnique ),
		fsmopt.OnStates(fsm.AnyState),      // it will also be preferable to use states
		fsmopt.Do(func(c tele.Context, state fsm.Context) error {
                       option := c.Data()
                       if len(option) >= 1 {
				checkboxes[option] = !checkboxes[option]
			}
			return c.Edit("please select options", getMultiselectKeyboard(checkboxes))
		}),
	),
)
````

**Comment by vitaliy-ukiru** [comment]
But I'll add helper function for create these endpoints.

Did that solve your problem?

**Comment by AlexeyKupershtokh** [comment]
Hey. Wow I didn't expect your answer to be such quick and thorough. Thank you so much.

This approach helps greatly and I would say doesn't require syntax sugar to the same extent as my prev example.

I have to admit I didn't expect that unique can be actually not unique. I'm new to telebot (+ filters + fsm) and just start trying to implement a few simple tasks to check if it's suitable and flexible enough for my needs.
